version: "3"
services:
  hmpps-prison-visits-testing-helper-api:
    build:
      context: .
    network_mode: "host"
    container_name: hmpps-prison-visits-testing-helper-api
    ports:
      - "8089:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
