server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/visit_scheduler
    username: visit_scheduler
    password: visit_scheduler

hmpps.auth.url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

visit-scheduler:
  api:
    timeout: 10s
    url: http://localhost:8081


sqs:
  provider: aws
  prison:
    events:
      queue:
        url: http://localhost:4566/sqs_hmpps_prison_visits_event_queue
      endpoint:
        url: http://localhost:4566
        region: eu-west-2