server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/visit_scheduler
    username: visit_scheduler
    password: visit_scheduler

hmpps.auth.url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

visit-scheduler:
  api:
    timeout: 10s
    url: http://localhost:8081

hmpps:
  sqs:
    provider: localstack
    queues:
      prisonvisitsevents:
        queue:
          url: http://sqs.eu-west-2.localhost.localstack.cloud:4566/000000000000/sqs_hmpps_prison_visits_event_queue
        endpoint:
          url: http://localhost:4566
          region: eu-west-2
