---
# Per environment values which override defaults in hmpps-prison-visits-testing-helper-api/values.yaml

generic-service:
  replicaCount: 1

  ingress:
    host: hmpps-prison-visits-testing-helper-api-staging.prison.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    VISIT-SCHEDULER_API_URL: https://visit-scheduler-staging.prison.service.justice.gov.uk
    PRISON_API_URL: https://prison-api-staging.prison.service.justice.gov.uk
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: visits-alerts-nonprod
  sqsAlertsQueueNames:
    - "book-a-prison-visit-dev-hmpps_prison_visits_event_queue"
    - "book-a-prison-visit-dev-hmpps_prison_visits_event_dlq"
  sqsAlertsOldestThreshold: 1
  sqsAlertsTotalMessagesThreshold: 1

