---
# Per environment values which override defaults in hmpps-prison-visits-testing-helper-api/values.yaml

generic-service:
  replicaCount: 1

  ingress:
    host: hmpps-prison-visits-testing-helper-api-dev.prison.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: "stdout"
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    VISIT-SCHEDULER_API_URL: https://visit-scheduler-dev.prison.service.justice.gov.uk
    PRISON_API_URL: https://prison-api-dev.prison.service.justice.gov.uk
    BOOKER-REGISTRY_API_URL: https://hmpps-prison-visit-booker-registry-dev.prison.service.justice.gov.uk
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

  scheduledDowntime:
    enabled: true

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: visits-alerts-nonprod
  businessHoursOnly: true
